apps/account/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from . import views

app_name = "account"
urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy("account:login"), permanent=False)),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="account/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),
]

source/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from mainpage.views import mainView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("", mainView, name="main"),
]

# MEDIA_URL로 들어오는 요청에 대해 MEDIA_ROOT 경로를 탐색한다.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "mainpage.views.page_not_found"
handler500 = "mainpage.views.internal_error"

src/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView
from mainpage.views import mainView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include('account.urls')),
    path('', mainView, name='main'),
]

apps/account/models.py
from django.db import models

# Create your models here.

apps/backtasks/models.py
from django.db import models
from django.utils import timezone
from uuid import uuid4
import ast
from .utils.tools import import_function_by_string
import logging

logger = logging.getLogger('django')

# Create your models here.
class Task(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    name = models.CharField(max_length=200)
    params = models.TextField()
    made_at = models.DateTimeField(auto_now_add=True)
    run_at = models.DateTimeField(null=True)
    
    class Meta:
        abstract = True

class WaitingTask(Task):
    def execute(self):
        '''
        WaitingTask의 name과 args, kwargs를 추출하고 해당 name의 함수를 찾아 직접 실행함.
        '''
        full_module = self.name
        args, kwargs = ast.literal_eval(self.params)
        func = import_function_by_string(full_module)
        func.execute(*args, **kwargs)
        
        ct = CompletedTask.objects.create(
            name=self.name,
            params=self.params,
            made_at=self.made_at,
            run_at=timezone.now())
        ct.save()
        logger.info('Task {} is completed.'.format(self.name))
        self.delete()

class CompletedTask(Task):
    pass

apps/mainpage/models.py
from django.db import models

# Create your models here.

apps/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

apps/account/views.py
from django.http import HttpRequest, HttpResponse
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from account.forms import UserForm

def signup(
    request: HttpRequest
) -> HttpResponse:
    '''
    회원가입 페이지.
    GET 요청시 회원가입 Form 페이지 렌더.
    POST 요청시 회원가입 절차 진행.

    Args:
        request (HttpRequest)

    Returns:
        HttpResponse
    '''
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect("main")
    else:
        form = UserForm()
    return render(request, "account/signup.html", {"form": form})

apps/backtasks/views.py
from django.shortcuts import render

# Create your views here.

apps/mainpage/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

# Create your views here.
def mainView(
    request: HttpRequest
) -> HttpResponse:
    '''
    메인 페이지 렌더

    Args:
        request (HttpRequest)

    Returns:
        HttpResponse
    '''
    return render(request, "main.html")

def page_not_found(
    request: HttpRequest, 
    exception
) -> HttpResponse:
    '''
    404 에러 대표 페이지 렌더

    Args:
        request (HttpRequest)
        exception (_type_)

    Returns:
        HttpResponse
    '''
    return render(request, "404.html", {})

def internal_error(
    request: HttpRequest
) -> HttpResponse:
    '''
    500 에러 대표 페이지 렌더

    Args:
        request (HttpRequest)

    Returns:
        HttpResponse
    '''
    return render(request, "500.html", {})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>기본 템플릿 v0.0.1</title>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    </head>
    <body>
        {% csrf_token %}
        <div class="main-body">
            <div class="service-logo">
                <a href="{% url 'main' %}" style="text-decoration:none; color:black;">
                    서비스 로고
                </a>
            </div>
            <div class="top-controllers">
                <div class="apptitle">
                    {% if pagetitle is None %}
                    기능 이름
                    {% else %}
                    {{ pagetitle }}
                    {% endif %}
                </div>
                <div class="account-controllers">
                    {% if user.is_authenticated %}
                    <button class="base-button account-button account-name">{{ user.username }}</button>
                    <button class="base-button account-button" url="{% url 'account:logout' %}" method="post">로그아웃</button>
                    </form>
                    {% else %}
                    <button class="base-button account-button account-login" url="{% url 'account:login' %}" method="get">로그인</button>
                    <button class="base-button account-button" url="{% url 'account:signup' %}" method="get">회원가입</button>
                    {% endif %}
                </div>
            </div>
            <div class="left-controllers">
                <a class="left-appbutton" href="">
                    <span class="material-symbols-outlined">
                        chat
                    </span>메뉴 자리</a>
            </div>
            <div class="incontents">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/marked.min.js' %}"></script>
    </body>
</html>

templates/main.html
{% extends "base.html" %}
{% block content %}
<div class="main-title">
    시작 페이지
</div>
{% endblock %}